
export const users = [
    {
        id: 1,
        photoURL: "https://static.vecteezy.com/system/resources/previews/029/271/069/non_2x/avatar-profile-icon-in-flat-style-female-user-profile-illustration-on-isolated-background-women-profile-sign-business-concept-vector.jpg",
        name: "Dominic Kihn",
        role: "Developer",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 2,
        photoURL: "https://static.vecteezy.com/system/resources/previews/029/271/069/non_2x/avatar-profile-icon-in-flat-style-female-user-profile-illustration-on-isolated-background-women-profile-sign-business-concept-vector.jpg",
        name: "Dominic Kihn",
        role: "Developer",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 3,
        photoURL: "https://static.vecteezy.com/system/resources/previews/004/819/327/original/male-avatar-profile-icon-of-smiling-caucasian-man-vector.jpg",
        name: "Dallas Daugherty",
        role: "User",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 4,
        photoURL: "https://img.freepik.com/premium-vector/woman-avatar-profile-round-icon_24640-14042.jpg",
        name: "Jo Ebert",
        role: "Admin",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 5,
        photoURL: "https://c8.alamy.com/zooms/9/c6f3f3c389b1482b8da4487bd00ad018/kfeagb.jpg",
        name: "Phil Wyman",
        role: "User",
        verified: "No",
        status: "Banned",
    },
    {
        id: 6,
        photoURL: "https://static.vecteezy.com/system/resources/previews/004/819/327/original/male-avatar-profile-icon-of-smiling-caucasian-man-vector.jpg",
        name: "Dallas Daugherty",
        role: "User",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 7,
        photoURL: "https://img.freepik.com/premium-vector/woman-avatar-profile-round-icon_24640-14042.jpg",
        name: "Jo Ebert",
        role: "Admin",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 8,
        photoURL: "https://c8.alamy.com/zooms/9/c6f3f3c389b1482b8da4487bd00ad018/kfeagb.jpg",
        name: "Phil Wyman",
        role: "User",
        verified: "No",
        status: "Banned",
    },
    {
        id: 9,
        photoURL: "https://static.vecteezy.com/system/resources/previews/029/271/069/non_2x/avatar-profile-icon-in-flat-style-female-user-profile-illustration-on-isolated-background-women-profile-sign-business-concept-vector.jpg",
        name: "Dominic Kihn",
        role: "Developer",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 10,
        photoURL: "https://static.vecteezy.com/system/resources/previews/004/819/327/original/male-avatar-profile-icon-of-smiling-caucasian-man-vector.jpg",
        name: "Dallas Daugherty",
        role: "User",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 11,
        photoURL: "https://img.freepik.com/premium-vector/woman-avatar-profile-round-icon_24640-14042.jpg",
        name: "Jo Ebert",
        role: "Admin",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 12,
        photoURL: "https://c8.alamy.com/zooms/9/c6f3f3c389b1482b8da4487bd00ad018/kfeagb.jpg",
        name: "Phil Wyman",
        role: "User",
        verified: "No",
        status: "Banned",
    },
    {
        id: 13,
        photoURL: "https://static.vecteezy.com/system/resources/previews/004/819/327/original/male-avatar-profile-icon-of-smiling-caucasian-man-vector.jpg",
        name: "Dallas Daugherty",
        role: "User",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 14,
        photoURL: "https://img.freepik.com/premium-vector/woman-avatar-profile-round-icon_24640-14042.jpg",
        name: "Jo Ebert",
        role: "Admin",
        verified: "Yes",
        status: "Active",
    },
    {
        id: 8,
        photoURL: "https://c8.alamy.com/zooms/9/c6f3f3c389b1482b8da4487bd00ad018/kfeagb.jpg",
        name: "Phil Wyman",
        role: "User",
        verified: "No",
        status: "Banned",
    },
]